apiVersion: apps/v1
kind: Deployment
metadata:
  name: BiddingExamination
  labels:
    app: BiddingExamination
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BiddingExamination
  template:
    metadata:
      labels:
        app: BiddingExamination
    spec:
      containers:
        - name: BiddingExamination
          image: username/BiddingExamination:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5